### ISSUE TITLE
No module naimed trainer

### ISSUE THREAD

**Issue by ghost** [deepsound-project/samplernn-pytorch#35]
Hello, 

when training, I get the following error. The module trainer doesn't seem to exist ??
```

cd .. && python train.py --exp TEST --frame_sizes 16 4 --n_rnn 2 --dataset piano
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from trainer.plugins import (
  File "/home/vincent/samplernn-pytorch/trainer/plugins.py", line 8, in <module>
    from torch.utils.trainer.plugins.plugin import Plugin
ModuleNotFoundError: No module named 'torch.utils.trainer'
```

**Comment by ghost** [comment]
Had to downgrade pytorch

**Comment by markhanslip** [comment]
can you remember which version you downgraded to? I just ran into the same issue
